name: Release Tag
on:
  push:
    branches:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: 버전 정보 추출
      run: |
        echo "version=${{ github.ref }}" >> "$GITHUB_OUTPUT"
        echo "test=${{ github.ref }}" >> "$GITHUB_OUTPUT"
      id: extract_version_name

    - name: test
      run: |
        echo ${{ steps.extract_version_name.outputs.version }}
        echo "release_version=$(echo ${{ steps.extract_version_name.outputs.test }} | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
    
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.extract_version_name.outputs.version }}
        release_name: ${{ steps.extract_version_name.outputs.version }}
