name: Release Api
on:
  pull_request:
    branches:
      - deploy/api
    types:
      - closed
    
permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: 버전 정보 추출
      run: |
        echo "${{ github.event.pull_request.title }}"
        echo "version=$(echo 'api-v${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        echo "version=$(echo 'api-v${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> "$GITHUB_OUTPUT"
      id: extract_version_name
    
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.extract_version_name.outputs.version }}
        release_name: ${{ steps.extract_version_name.outputs.version }}
